export let tiny       = 'screen and (max-width: 35.9375em)'
export let smallOnly  = 'screen and (max-width: 39.9375em)'
export let mediumOnly = 'screen and (min-width: 64em) and (max-width: 74.9375em)'
export let mediumUp   = 'screen and (min-width: 64em)'
export let largeOnly  = 'screen and (min-width: 75em) and (max-width: 80em)'
export let largeUp    = 'screen and (min-width: 75em)'
